### ISSUE TITLE
Demo app: DTSTART and UNTIL of rule.toString() don't match the input

### ISSUE THREAD

**Issue by joelz** [jakubroztocil/rrule#257] opened 2018-08-14 04:18 UTC
- rrule version: latest ? (the version used in the demo app)
- operating system: windows 10 
- my local timezone : +0800

I was checking the demo app on http://jakubroztocil.github.io/rrule/

My input is :

![image](https://user-images.githubusercontent.com/469974/44071336-16da59d4-9fbb-11e8-99f7-1860a9ad9779.png)

 Actual output:

![image](https://user-images.githubusercontent.com/469974/44071368-411b0fea-9fbb-11e8-937d-ca034cc76db5.png)

My local timezone is +0800, and I think the DTSTART and UNTIL in `rule.toString()` are wrong. They should be `20180731T160000Z` and `20180831T155900Z`.

Or am I missing some points ?

Hope someone can help.

**Comment by davidgoli** [comment] 2018-08-14 05:31
@joelz I just noticed this today and filed it earlier: #256. Totally legitimate, but I'm closing this as a duplicate. Hope to get it fixed soon!

**Comment by davidgoli** [comment] 2018-08-15 16:56
@joelz Turns out this is just a quirk of browser UX. It will work if you ensure both date and time are filled in for dtstart and until. See: https://stackoverflow.com/questions/39209401/html-datetime-local-change-event

**Comment by joelz** [comment] 2018-08-16 01:41
I did fill in both date and time for dtstart and until in the input area, which can be found in the picture I posted above. 

I checked the demo app code , and I think I may found where the issue is. Let me go through this:

1. I select 2018-08-01 00:00 for dtstart, which means dtstart is `20180801T000000+0800`, cause I am in time zone +0800
2. when the demo code set `rule=`, it takes `new Date(2018, 6, 31, 16, 0, 0)` as dtstart. I think this is where the issue is. Demo code converts the datetime I select ( `20180801T000000+0800`) into UTC, gets the result `20180731T160000Z` and use this result to `new Date(2018, 6, 31, 16, 0, 0)`.  When you use `new Date()` without the time zone info, it takes the input in the local time of the computer it's running on. So `new Date(2018, 6, 31, 16, 0, 0)` in my computer gets a `20180731T160000+0800`. This dtstart is not what I select, it is 8 hours earlier.
3. So with a dtstart `20180731T160000+0800`, `rule.toString()` will get a `20180731T080000Z` as dtstart. This step is right, cause `20180731T160000+0800` is `20180731T080000Z`

**Comment by davidgoli** [comment] 2018-08-16 02:36
@joelz OK, I see what the issue is. I have a fix for it (#262)

**Closed** 2018-08-16 03:01 UTC

**Comment by davidgoli** [comment] 2018-08-16 03:03
@joelz I've pushed the fix up to the demo app, please verify you see the expected output. Thanks!

**Comment by joelz** [comment] 2018-08-16 03:30
@davidgoli I have checked the demo app, the `rule =` and `rule.toString()` now match, and the `rule.all()` are right.

Another suggestion: add some text to inform users that when there are values selected in `dtstart` and `until`,  these values will be treated as UTC datetime. With this assumption, selected values, the `rule =` and `rule.toString()`  will match.
