### ISSUE TITLE
Hour gap in time-zones that utilize summer/winter time switch?

### ISSUE THREAD

**Issue by sick-sad-world** [jakubroztocil/rrule#285] opened 2018-10-01 09:48 UTC
Using this awesome tool in conjunction with Microsoft Exchange Web Services for email client app.

- Occurrences generated in order to fit EWS Repeating patterns. But this question is related to all of them. Simplest one DAILY for example. Dates provided as ISOStrings like so `2018-10-01T09:33:32.562Z`
```
      new RRule({
        freq: RRule.DAILY,
        dtstart: new Date(Date.parse(Start)),
        interval: Recurrence.Interval,
        tzid: 'local',
        wkst: RRule.SU
      })
```
- Expected output (OWA)
![expected_owa](https://user-images.githubusercontent.com/5785120/46281757-3c1bc380-c578-11e8-9d12-f8c9d2e65ee3.png)
- Actual output
![actual_result](https://user-images.githubusercontent.com/5785120/46281774-463dc200-c578-11e8-9410-5b1153234ea4.png)

```
"rrule": "^2.5.5",
"luxon": "^1.3.3",
```
- Windows 10ENT 
- Mon Oct 01 2018 12:30:15 GMT+0300 (FLE Daylight Time)

**Comment by davidgoli** [comment] 2018-10-01 21:38
This is resolved and a dupe of #279 #233 #230 and others, and the fix involves simply passing in a UTC date to begin with, but I'm wondering if there might actually be a library-level fix here somehow to "normalize" dates passed in so they're always treated as UTC even if they're not originally.

**Closed by davidgoli** 2018-10-01 21:38 UTC
