### ISSUE TITLE
EXDATE DST issue (reopen #292)

### ISSUE THREAD

**Issue by harryy2510** [jakubroztocil/rrule#293] opened 2018-10-21 01:33 UTC
<img width="1680" alt="screenshot 2018-10-21 at 6 34 55 am" src="https://user-images.githubusercontent.com/7416971/47262062-8b13a380-d4fb-11e8-9a22-6fe06e119775.png">

@davidgoli  I agree to the point that if the recurrence is at 7pm, it will remain at 7pm whether or not dst and the EXDATE should be too 7pm. But the case I am trying to explaing is, while in DST, the UTC time will change as 8pm instead of 7pm.

- 7pm in America/Los_Angeles on 30th October is 2am 31st UTC

`moment().tz('America/Los_Angeles').month(9).date(30).hour(19).minute(0).second(0).millisecond(0).toISOString()` will result in `2018-10-31T02:00:00.000Z`

- 7pm in America/Los_Angeles on 10th November is 3am 11th UTC

`moment().tz('America/Los_Angeles').month(10).date(10).hour(19).minute(0).second(0).millisecond(0).toISOString()` will result in `2018-11-11T03:00:00.000Z`

While parsing the rule, the UTC time itself is adjusted during dst. so should the EXDATE should also resemble to adjusted time?

`const rruleSet = new RRuleSet();
    rruleSet.exdate(new Date(moment(this.event.start).startOf('d').toISOString()));`

This is the piece of code I am using for setting the EXDATE which gives me the result with two different offsets depending on standard or dst time.

_Originally posted by @harryy2510 in https://github.com/jakubroztocil/rrule/issues/292#issuecomment-431630982_

**Comment by davidgoli** [comment] 2018-10-21 01:40
Duplicate of #292

**Closed by davidgoli** 2018-10-21 01:40 UTC

**Comment by timruo** [comment] 2018-10-25 15:02
Had similar issues with DST while running on my local environment (OSX). I switched my TZ to UTC (using this https://gist.github.com/nick-desteffen/1126771) and the problems disappeared.
