### ISSUE TITLE
How can I install rrule without luxon library?

### ISSUE THREAD

**Issue by sanjitkung** [jakubroztocil/rrule#382] opened 2019-12-19 14:51 UTC
This is not an issue just a question.

I know, I can pass ` --no-optional` to ignore the optional dependencies while installing package like this:

```
npm install rrule --no-optional
```

But if I run 'npm run install' again on my project. it installs the luxon library.

Either I have to ignore optional dependencies from all the packages that I have installed or I have to install luxon.

Is there any way I can install rrule from npm with luxon ?

**Comment by thefliik** [comment] 2019-12-19 17:25
So I could be mistaken, but I *think* that luxon is actually a required dependency (which can be viewed as a bug, given that it is clearly *intended* as an optional dependency). See this comment on another issue for more info: https://github.com/jakubroztocil/rrule/issues/344#issuecomment-533704894.

Both myself and the original issue maker have only tested using a webpack build process though.

I think the underlying issue needs to be fixed with a breaking change that creates a second, separate package entry point for rrule.

In answer to your question though:

> Is there any way I can install rrule from npm with luxon ?

No, I don't think so.

**Comment by davidgoli** [comment] 2019-12-19 22:39
I intend to work on a minor version bump release that will remove luxon. Unfortunately, I'm not sure there's a way to do this without requiring people who desire timezone support to implement their own timezone conversion function, whether using Luxon or another library, which could be a source of uninentional bugs.

An alternative might be to reimplement a library that's *just* the timezone logic without the rest of Luxon, which is a bit more work but probably not impossible.

**Comment by thefliik** [comment] 2019-12-20 00:38
@davidgoli simply providing two entry points to rrule (the second one needed for timezone support) seems reasonable and easy to implement (I'm happy to provide the PR). It would be a breaking change though. And it would complicate the rrule setup process for folks using luxon. 

As I noted over in https://github.com/jakubroztocil/rrule/issues/344#issuecomment-533704894, given how rarely the issue of removing luxon comes up, it also seems reasonable to just make luxon a required dependency of rrule. Again, it appears that luxon is currently a required dependency, and 99% of folks don't notice soo...?

**Comment by davidgoli** [comment] 2020-03-12 19:44
Duplicate of #344.

**Closed by davidgoli** 2020-03-12 19:44 UTC
