### ISSUE TITLE
Ordinal numbers should be sorted numerically not alphabetically

### ISSUE THREAD

**Issue by JofArnold** [jakubroztocil/rrule#139] opened 2016-05-04 08:29 UTC
I.e.

"every month on the 1st, 10th, 11th, 12th, 13th, 14th, 15th, 16th, 17th, 18th, 19th, 2nd, 20th, 21st, 22nd, 23rd, 24th, 25th, 26th, 27th, 28th, 29th, 3rd, 30th, 31st, 4th, 5th, 6th, 7th, 8th and 9th until May 4, 2020"

Should be shown as

"every month on the 1st, 2nd, 3rd, 4th, ..."

**Comment by rbj325** [comment] 2017-04-07 17:38
This is a duplicate of:  https://github.com/jakubroztocil/rrule/issues/101

**Comment by espen** [comment] 2018-01-16 16:27
Closed in favour of #101

**Closed by espen** 2018-01-16 16:27 UTC
