### ISSUE TITLE
Release Tagging and Change history in Github not updated

### ISSUE THREAD

**Issue by iamvajid** [jakubroztocil/rrule#242] opened 2018-08-07 02:06 UTC
@jakubroztocil - The change history doesn't seem to be maintained here https://github.com/jakubroztocil/rrule/releases. Its showing a very old version as latest, unable to track what changed in new releases. My server build was breaking and when i checked, noticed that rrule@latest is not being downloaded, for which there is an open issue #241 . Was looking through the updates going on and was surprised when there was no release history. Respect your time commitment, happy to help if more hands needed

**Comment by iamvajid** [comment] 2018-08-07 02:51
Thanks for the comments @arolson101 . Yes, did it.

**Comment by davidgoli** [comment] 2018-08-07 19:35
@iamvajid 2.3.2 should be workable.
@arolson101 I'm happy to help with release tagging etc. but I still don't have github access.

**Comment by jakubroztocil** [comment] 2018-08-09 11:33
@davidgoli  I've added you to this repo as a collaborator.

Please tag the appropriate commits with `vX.X.X` as I've done in the past —  https://github.com/jakubroztocil/rrule/tags — and also include all changes in the Changelog section of in `README.md` (we might also wanna move the changelog to its own `CHANGELOG.md`). 

@davidgoli @arolson101 & co.: Thanks for all the great contributions. Really happy to see the project continues going forward.

**Comment by jakubroztocil** [comment] 2018-08-09 11:43
Also, if possible, please try to keep the online demo — https://jakubroztocil.github.io/rrule/ — up-to-date by pushing to the `gh-pages` branch.

The demo might need some love after all the recent changes (https://github.com/jakubroztocil/rrule/tree/master/demo).

**Comment by iamvajid** [comment] 2018-08-09 16:01
Great coordination @jakubroztocil . I loved this library and is making use of this in my project. Would love to contribute to the library. Where & how should i start ?

**Comment by davidgoli** [comment] 2018-08-09 18:34
@iamvajid thanks for your interest! I'd say we could use a lot of help right now going through outstanding issues and determining if they still reproduce, and if so, finding repro steps, otherwise, closing them out. Once we have a solid list of reproduceable bugs in the issues list, we can start fixing them. I'd recommend starting from the top.

Additionally, I just created a pull request template for new PRs that details what a good PR looks like, including linking to existing issues and writing tests for the change.

Thanks for helping out!

**Comment by davidgoli** [comment] 2018-08-09 19:31
@jakubroztocil I've added tags and updated the releases... I don't have context on releases before 2.2.9 so there may be some gaps; hopefully going forward we can have better release notes as we release.

**Closed by davidgoli** 2018-08-09 19:31 UTC
