### ISSUE TITLE
Issue with weekly rule

### ISSUE THREAD

**Issue by acmayberry** [jakubroztocil/rrule#230] opened 2018-08-02 02:13 UTC
I'm using version 2.2.9 and the following rule:

FREQ=WEEKLY;DTSTART=20181031T180000Z;UNTIL=20181115T050000Z

This rule produces these dates in the browser demo:

1 | Wed | Oct | 31 | 2018 | 14:00:00 | GMT-0400 | (Eastern Daylight Time)
2 | Wed | Nov | 07 | 2018 | 14:00:00 | GMT-0500 | (Eastern Standard Time)
3 | Wed | Nov | 14 | 2018 | 14:00:00 | GMT-0500 | (Eastern Standard Time)

It produces these dates in both the iOS simulator and Android emulator running a react native app:

1 | Wed | Oct | 31 | 2018 | 14:00:00 | GMT-0400 | (Eastern Daylight Time)
2 | Tue | Nov | 06 | 2018 | 14:00:00 | GMT-0500 | (Eastern Standard Time)
3 | Wed | Nov | 14 | 2018 | 14:00:00 | GMT-0500 | (Eastern Standard Time)

These dates are generated using the following code:

import {RRule,rrulestr} from 'rrule';
...
let r = rrulestr('FREQ=WEEKLY;DTSTART=20181031T180000Z;UNTIL=20181115T050000Z');
let rdates = r.all();

**Comment by jonhageman** [comment] 2018-08-02 20:33
I am experiencing the same problem with the following rule: 
FREQ=WEEKLY;DTSTART=20181101T040000Z;INTERVAL=1;WKST=MO;BYDAY=TH;BYHOUR=0;BYMINUTE=0;BYSECOND=0

It seems to have trouble accounting for the end of daylight savings time. It works in your demo, but in my app, the first occurrence AFTER daylight savings time ends (November 4) appears one day early.

**Comment by jonhageman** [comment] 2018-08-03 13:59
I found the issue In dateutil.js, the method fromOrdinal (lines 77-83) does not need to subtract and then re-add the time zone offset. When the time zone of the ORINDAL_BASE and passed in ordinal value are the same, the net result is 0 anyway. But in the case of time zones that go on and off daylight savings time, like Eastern time zone, the time zone offset for the ORDINAL_BASE and the time zone offset for the passed in ordinal value will be different when the ordinal date is in daylight savings and the ORDINAL_BASE is not, resulting in a date value that is 1 hour less than what it should be.

Example: ORDINAL_BASE is Jan 1, 1970 (EST) but ordinal is November 1, 2018 (EDT). The time zone offset from the ORDINAL_BASE is 5 hours but the tine zone offset from the ordinal is 4 hours.

dateutil.ORDINAL_BASE.getTime(): -2208970800000
dateutil.tzOffset(dateutil.ORDINAL_BASE): 18000000
millisecsFromBase: 3750624000000
dateutil.tzOffset(new Date(millisecsFromBase)): 14400000

fromOrdinal returns “Wed Nov 07 2018 23:00:00 GMT-0500 (Eastern Standard Time)”

but the correct value should be “Thu Nov 08 2018 00:00:00 GMT-0500 (Eastern Standard Time)”

I created Pull Request #232 to resolve the issue.

**Comment by davidgoli** [comment] 2018-08-03 21:53
Another dupe of #233

**Comment by davidgoli** [comment] 2018-08-09 18:13
Please reopen if you are still having issues.

**Closed by davidgoli** 2018-08-09 18:13 UTC

**Comment by jonhageman** [comment] 2018-08-09 18:18
I can't confirm that it is working yet because the latest release has introduced another issue with the between method. It seems the between method calculates a recurrence at 00:00:00 but then converts it to the timezone afterward. For Eastern time zone, this results in a day 4 hours behind the correct recurrence, which ends up being a day earlier than expected. I am still reading through the code for a suggested solution.
