### ISSUE TITLE
Default test fails

### ISSUE THREAD

**Issue by enrimr** [jakubroztocil/rrule#152] opened 2016-08-05 07:30 UTC
```
- testStrKeywords
1) testStrNWeekDay [every year on the 1st Tuesday and last Thursday for 3 times] [FREQ=YEARLY;COUNT=3;BYDAY=+1TU,-1TH;DTSTART=19970902T090000Z]
```

  272 passing (2s)
  10 pending
  1 failing

  1) rrulestr testStrNWeekDay [every year on the 1st Tuesday and last Thursday for 3 times] [FREQ=YEARLY;COUNT=3;BYDAY=+1TU,-1TH;DTSTART=19970902T090000Z]:

```
  AssertionError:  - 1/3
  + expected - actual

  -Thu Dec 25 1997 10:00:00 GMT+0100 (CET)
  +Thu Dec 25 1997 11:00:00 GMT+0100 (CET)

  at assertDatesEqual (test/lib/utils.js:20:12)
  at Context.<anonymous> (test/lib/utils.js:103:5)
```

npm ERR! Test failed.  See above for more details.

**Comment by espen** [comment] 2018-01-16 12:33
Closing due to duplicate of https://github.com/jakubroztocil/rrule/issues/136

**Closed by espen** 2018-01-16 12:33 UTC
