### ISSUE TITLE
2.3.2 is very slow

### ISSUE THREAD

**Issue by davidp-inova** [jakubroztocil/rrule#243] opened 2018-08-08 14:35 UTC
Latest version 2.3.2 is very slow at parsing rules. Reverted to 2.2.9 and now it works fast again.

**Comment by davidgoli** [comment] 2018-08-08 17:39
@davidp-inova can you please provide a repro case for benchmarking? thanks

**Comment by davidp-inova** [comment] 2018-08-09 07:11
Example code:
```
const options = RRule.parseString(rrule);
options.dtstart = moment.unix(startDate.seconds).toDate();
options.until = moment.unix(endDate.seconds).toDate();
const calendarRule = new RRule(options);
const sd = new Date(startOfWeek.clone().toISOString());
const ed = new Date(startOfWeek.clone().endOf('day').toISOString());
                
let isTodayContained = calendarRule.between(sd, ed);
```

**Comment by davidgoli** [comment] 2018-08-09 07:33
@davidp-inova could you share example values for `rrule`, `startDate`, `endDate`, and `startOfWeek`?

**Comment by davidgoli** [comment] 2018-08-13 00:43
@davidp-inova There appears to be no noticeable difference in the runtimes our test suite under 2.2.9 vs 2.3.4, excluding tests that have been added since then. Without knowing what values you're using for your code, I won't be able to reproduce the issue you're seeing and will have to close this issue.

**Comment by nickarora** [comment] 2018-08-16 00:59
I ran the above code snippet on both versions several times using the following variables:

```
const startDate = DateTime.local(2017, 10, 10)
const endDate = DateTime.local(2019, 10, 10)
const rrule = 'FREQ=DAILY;INTERVAL=1'
const sd = DateTime.local().startOf('day').toJSDate()
const ed = DateTime.local().endOf('day').toJSDate()
```

I found that `2.3.3` ran at comparable speeds to `2.2.9` -- both averaging about 8ms.

**Comment by davidgoli** [comment] 2018-09-13 23:13
Closing due to lack of repro

**Closed by davidgoli** 2018-09-13 23:13 UTC
Labels: needs info
