### ISSUE TITLE
Recurrence issue in monthly

### ISSUE THREAD

**Issue by nketha** [jakubroztocil/rrule#223] opened 2018-07-19 12:22 UTC
Hi,

1) In weekly showing correct occurrences with current date i.e(2018-07-19). showing below screen shot
![image](https://user-images.githubusercontent.com/39990755/42941542-b438e826-8b7a-11e8-86f4-0b9238cc314d.png)

2) Same scenario in monthly am tring with current month i.e (July).showing below screen shot,but here ignore the current month. actually out put occurrences was 3 but here showing 2 occurrences . 
![image](https://user-images.githubusercontent.com/39990755/42941883-c9d339b0-8b7b-11e8-87d6-0f359da5693e.png)

My question is: Why ignore the current month in monthly?

**Comment by arvanis** [comment] 2018-07-24 13:38
I had similar issues and it seems to be fixed by recently merged pr: https://github.com/jakubroztocil/rrule/pull/213 . @jakubroztocil @arolson101 could you push the latest version on npm?

**Comment by arvanis** [comment] 2018-07-24 13:51
I had similar issues and it seems to be fixed by recently merged pr: #213
However, the build fails. I think that the tests are bugged too :P

**Comment by davidgoli** [comment] 2018-08-03 21:54
Can you please copy/paste the text of the RRULEs to reproduce (not in image screenshots)?

**Comment by nketha** [comment] 2018-08-06 05:03
1) In weekly showing correct occurrences with current date i.e(2018-08-06)
 Frequency: Weekly
Start Time: Mon Aug 06 2018 10:30:00 GMT+0530 (India Standard Time)
 End Time: Mon Oct 08 2018 11:00:00 GMT+0530 (India Standard Time)

VM400:251 (10) [Mon Aug 06 2018 10:30:00 GMT+0530 (India Standard Time), Mon Aug 13 2018 10:30:00 GMT+0530 (India Standard Time), Mon Aug 20 2018 10:30:00 GMT+0530 (India Standard Time), Mon Aug 27 2018 10:30:00 GMT+0530 (India Standard Time), Mon Sep 03 2018 10:30:00 GMT+0530 (India Standard Time), Mon Sep 10 2018 10:30:00 GMT+0530 (India Standard Time), Mon Sep 17 2018 10:30:00 GMT+0530 (India Standard Time), Mon Sep 24 2018 10:30:00 GMT+0530 (India Standard Time), Mon Oct 01 2018 10:30:00 GMT+0530 (India Standard Time), Mon Oct 08 2018 10:30:00 GMT+0530 (India Standard Time)]

2) Same scenario in monthly am tring with current month i.e (august). here ignore the current month. actually out put occurrences was 3 but here showing 2 occurrences .
Frequency: Monthly

Start Time: Mon Aug 06 2018 10:30:00 GMT+0530 (India Standard Time)
 End Time: Mon Oct 08 2018 11:00:00 GMT+0530 (India Standard Time)
 
(2) [Wed Sep 05 2018 10:30:00 GMT+0530 (India Standard Time), Fri Oct 05 2018 10:30:00 GMT+0530 (India Standard Time)]
0
:
Wed Sep 05 2018 10:30:00 GMT+0530 (India Standard Time) {}
1
:
Fri Oct 05 2018 10:30:00 GMT+0530 (India Standard Time) {}

**Comment by davidgoli** [comment] 2018-08-10 23:47
@nketha I'm not sure I understand what you expect the behavior to be. It would help greatly if each date were on its own line.

I also fixed a major issue with v2.3.4. Can you confirm that you still see your issue with v2.3.4?

**Closed** 2018-08-13 01:07 UTC
